### ISSUE TITLE
Any future for project?

### ISSUE THREAD

**Issue by Ramazan804** [treviasxk/UNanite#4]
Will this project gonna get any updates in future? It would be so good and cool to have an open source alternative to Nanite in unity! Also I wanna ask about build support and if it does work on builds or not.

**Comment by treviasxk** [comment]
Thanks for commenting, at the moment this project is not running on builds, as the initial stage of the project I made it only run in the Editor.

I made a new update, but I haven't uploaded it to the repository at the moment due to a problem with Whinarn's UnityMeshSimplifier package, when reducing the meshes it creates holes or destroys the mesh completely in objects with complex meshes (image below as an example of a humanoid), I'm looking for an alternative for this so I can add it to the project.

![image](https://github.com/user-attachments/assets/1a9ecaf5-00fe-475e-a3e8-260a2e9c9680)
